### PR TITLE
Use JGO_CACHE_DIR to specify cache dir within conda env

### PR DESCRIPTION
**Pull request by hanslovsky**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)

Bumped the build number because we do not have a new release of `jgo` yet. We should wait with this PR until we have that release, otherwise the environment variables will not have any effect. Check list before merge:
 - [x] release `jgo-0.2.0`
 - [x] update recipe version to `0.2.0`
 - [x] reset build number to `1000`
 - ~run test with simple jar~

Is this PR a fix for #1? Or are there other issues in there that would need to be adressed separately?

### CODE REVIEW

**Comment by ctrueden** [comment]
https://pypi.org/project/jgo/0.2.0/
https://github.com/scijava/jgo/releases/tag/0.2.0

**Comment by jakirkham** [comment]
Should we create the `JGO_CACHE_DIR` as part of the build? Also if we do that, we may need to leave a dummy file in there to ensure the directory is kept in the package.

**Comment by hanslovsky** [comment]
I don't think there is any need to create it as part of the build. `jgo` will create it as needed.

**Comment by hanslovsky** [comment]
Might need to forgo any testing with calls to `jgo` until we have the `auto` link-mode: scijava/jgo#22, failure log from linux builds:
```
ERROR 2018-11-27 19:39:42,594: [Errno 18] Invalid cross-device link: '/home/conda/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.2.50/kotlin-stdlib-1.2.50.jar' -> '/home/conda/feedstock_root/build_artifacts/jgo_1543347517038/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/jgo/org/scijava/jgo-test/0.1.0/kotlin-stdlib-1.2.50.jar'
```

**Comment by hanslovsky** [comment]
Will remove the tests from this PR, testing will need to wait until scijava/jgo#22, scijava/jgo#24, and scijava/jgo#25 are resolved.

After that, we can run tests like this:
```yaml
test:
  requires:
    - openjdk
    - maven
  commands:
    - test "$(jgo -r ij=https://maven.imagej.net/content/groups/public org.scijava:jgo-test:0.1.0 yay jgo!)" = "yay jgo!"  # [unix]
    - for /f %%i in ('jgo -r ij=https://maven.imagej.net/content/groups/public org.scijava:jgo-test:0.1.0 yay jgo!') do set JGO_OUTPUT="%%i"; if not "%JGO_OUTPUT%" == "yay jgo!" exit 1  # [win]

**Review by hadim — APPROVED** [review]

**Comment by hadim** [comment]
LGTM after everything is green. It's good to have sanity tests in the recipe.

**Comment by ctrueden** [comment]
> Invalid cross-device link

Ah ha, I warned you, didn't I? 😜 

Thanks so much for working on this, guys.

**Pull request merged**
